server:
  port: 8081

spring:
  application:
    name: auth-service
  
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/ekart_auth_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration

eureka:
  client:
    enabled: false

jwt:
  secret: mysupersecurekeymysupersecurekey12345678
  expiration: 3600000
  refresh-expiration: 604800000

# Admin & User Configuration
app:
  admin:
    email: admin@ekart.com
    password: Admin@123
    name: Super Admin
    phone: "+91-9999999999"
    role: ROLE_ADMIN
  default-user:
    email: user@ekart.com
    password: User@123
    name: Test User
    phone: "+91-8888888888"
    role: ROLE_USER

logging:
  file:
    path: logs/
    name: logs/auth-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: INFO
    com.infy.ekart: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr([%X{requestId:-}]){cyan} %-5level %logger{20} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  show-actuator: false