server:
  port: ${PORT:8085}
spring:
  application:
    name: notification-service
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      client:
        url:
        - ${SPRING_BOOT_ADMIN_URL:http://Admin-Server:1111/}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://Service-Registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  health:
    mail:
      enabled: false
  tracing:
    enabled: false
app:
  email:
    from: ${MAIL_FROM}
    from-name: eKart Store
  base-url: ${APP_BASE_URL}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
logging:
  file:
    path: logs/
    name: logs/notification-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: INFO
    com.infy.ekart: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"
