server:
  port: 8085

spring:
  application:
    name: notification-service
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: aashu.infy@gmail.com
    password: niop uocj elrz hfab
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    enabled: false

app:
  email:
    from: aashu.infy@gmail.com
    from-name: eKart Store
  base-url: ${APP_BASE_URL:http://localhost:5173}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true

logging:
  file:
    path: logs/
    name: logs/notification-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: INFO
    com.infy.ekart: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"