spring:
  application:
    name: Admin-Server
  boot:
    admin:
      discovery:
        enabled: true
server:
  port: ${PORT:1111}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: false
